### ISSUE TITLE
ConsoleRawStream. Where do I import it from?

### ISSUE THREAD

**Issue by laat** [philmander/browser-bunyan#48]
```ts
import {  ConsoleRawStream } from 'browser-bunyan'; // compilation error in 1.6.2
```
It is exported and inlined in the all the JS-file inside the brower-bunyan package, but it's types are not exported it in the TypeScript definition.

This happened when bumping from 1.5.3 to 1.6.2.

The documentation might suggest that I should import from `@browser-bunyan/console-raw-stream` instead, but since it's already inlined in `browser-bunyan` doesn't that lead to duplicate code in my bundle?

**Comment by philmander** [comment]
Hi @laat . 

Thanks for pointing this out, I'd overlooked that the built-in streams were re-exported from the main package when I added the typings. 

`import { ConsoleFormattedStream, ConsolePlainStream, ConsoleRawStream } from 'browser-bunyan';` should now compile in `browser-bunyan@1.6.3`

**Comment by laat** [comment]
Thanks 👍
